package core;

public enum PlayerAttributes {
    HEIGHT,
    STRENGTH,
    SPEED,
    INSIDE_SCORING,
    MID_SCORING,
    THREE_P_SCORING,
    DUNK,
    OFFENSIVE_REBOUND,
    DEFENSIVE_REBOUND,
    INSIDE_DEFENSE,
    PERIMETER_DEFENSE,
    ASSIST,
    TURNOVER
}
