package core;

public enum TeamAttributes {
    HEIGHT,
    STRENGTH,
    SPEED,
    INSIDE_SCORING,
    MID_SCORING,
    THREE_P_SCORING,
    DUNK,
    FREE_THROW,
    OFFENSIVE_REBOUND,
    DEFENSIVE_REBOUND,
    INSIDE_DEFENSE,
    PERIMETER_DEFENSE,
    ASSIST,
    TURNOVER
}
