package gameplay;

public enum TeamStat {
    TEAM_PTS,
    TEAM_TWO_POINT_MADE,
    TEAM_TWO_POINT_ATTEMPTS,
    TEAM_THREE_POINT_MADE,
    TEAM_THREE_POINT_ATTEMPTS,
    TEAM_ASSIST,
    TEAM_STL,
    TEAM_BLK,
    TEAM_DRB,
    TEAM_ORB,
    TEAM_FREE_THROW_MADE,
    TEAM_FREE_THROW_ATTEMPTS,
    TEAM_TOV,
    TEAM_FOULS

}